# Generated by Django 2.0.5 on 2018-08-31 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True, verbose_name='Address')),
                ('is_company', models.BooleanField(default=False, verbose_name='Company Token')),
                ('exchange', models.CharField(blank=True, max_length=60, null=True, verbose_name='Exchange')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses with LEDU',
            },
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('quantity', models.FloatField(default=0, verbose_name='Current Quantity(Token)')),
                ('percentage', models.FloatField(default=0, verbose_name='Current Percentage')),
                ('prev_quantity', models.FloatField(default=0, verbose_name='Previous Quantity(Token)')),
                ('prev_percentage', models.FloatField(default=0, verbose_name='Previous Percentage')),
                ('change', models.FloatField(default=0, verbose_name='Change')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_address', to='product.Address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Holder',
                'verbose_name_plural': 'Tracking LEDU Holders',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=66, verbose_name='Hash')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='TimeStamp')),
                ('quantity', models.FloatField(default=0, verbose_name='Quantity')),
                ('_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_from_address', to='product.Address', verbose_name='From')),
                ('_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tx_to_address', to='product.Address', verbose_name='To')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'All LEDU Transactions',
            },
        ),
        migrations.CreateModel(
            name='Mover',
            fields=[
            ],
            options={
                'verbose_name': 'Mover',
                'verbose_name_plural': 'Tracking LEDU Transaction to Exchange sites',
                'proxy': True,
                'indexes': [],
            },
            bases=('product.transaction',),
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking',
                'verbose_name_plural': 'Tracking LEDU Transaction History',
                'proxy': True,
                'indexes': [],
            },
            bases=('product.transaction',),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('hash', '_from', '_to', 'timestamp', 'quantity')},
        ),
    ]
