# Generated by Django 2.0.5 on 2018-08-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('email_password', models.CharField(max_length=30, verbose_name='Email Password')),
                ('bitforex_password', models.CharField(max_length=30, verbose_name='Bitforex Password')),
                ('access_key', models.CharField(blank=True, max_length=31, null=True, verbose_name='Access Key')),
                ('secret_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='Secret Key')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['pk'],
            },
        ),
    ]
