# Generated by Django 2.0.5 on 2018-08-31 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('volume_usd', models.FloatField(verbose_name='Volume USD(24h)')),
                ('volume_btc', models.FloatField(verbose_name='Volume BTC(24h)')),
                ('volume_native', models.FloatField(verbose_name='Volume Native(24h)')),
                ('price_usd', models.FloatField(verbose_name='Price USD')),
                ('price_btc', models.FloatField(verbose_name='Price BTC')),
                ('price_native', models.FloatField(verbose_name='Price Native')),
                ('percent', models.FloatField(verbose_name='Volume(%)')),
                ('current_price', models.FloatField(default=0.0, verbose_name='Current Price')),
                ('lowest_ask', models.FloatField(default=0.0, verbose_name='Lowest Sell Order')),
                ('highest_bid', models.FloatField(default=0.0, verbose_name='Highest Buy Order')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('rate', models.FloatField(verbose_name='Price')),
                ('type', models.BooleanField(verbose_name='Order Type')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('pair', models.CharField(max_length=8, verbose_name='Pair')),
                ('url', models.URLField(verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='orderbook',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinmarketcap.Source'),
        ),
        migrations.AddField(
            model_name='market',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinmarketcap.Source'),
        ),
    ]
