# Generated by Django 2.0.5 on 2018-08-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketcap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='timestamp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
